#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE=".env"

banner "LinkRouter Developer ID + notarization"

# ── 1. Paid Apple Developer Program ───────────────────────────────────────
stage "Apple Developer Program"
say "Notarization needs a paid Apple Developer Program membership (\$99/year)."
open_url "https://developer.apple.com/account"
step "Sign in. You should land on your developer account, not the enrollment form."
step "If Apple asks you to enroll or pay, finish that first, then re-run this wizard."
pause "Press Enter when you can see your developer account."

# ── 2. Developer ID Application certificate ───────────────────────────────
stage "Developer ID Application certificate"
say "This certificate is what Gatekeeper trusts for apps shipped outside the Mac App Store."
say "Easiest path is Xcode, not the Certificates website."
step "Open Xcode → Settings (⌘,) → Accounts."
step "Select your Apple ID, then the team on the right → Manage Certificates…"
step "Click + (bottom left) → Developer ID Application."
step "Skip this if that list already shows Developer ID Application with your name."
note "A new cert can take a few seconds to appear in Keychain Access."
pause "Press Enter when the certificate exists."

# ── 3. Export .p12 ────────────────────────────────────────────────────────
stage "Export the certificate as a .p12"
say "CI needs the cert plus its private key as a password-protected .p12."
if command -v open >/dev/null 2>&1; then
  open -a "Keychain Access" >/dev/null 2>&1 || true
  note "Opened Keychain Access."
fi
step "Sidebar: login → My Certificates."
step "Find Developer ID Application: Your Name (TEAMID)."
step "Right-click it → Export \"…\" → File Format: Personal Information Exchange (.p12)."
step "Save it somewhere local (Downloads is fine) and set an export password. Remember it."
ask P12_PATH "Path to the .p12 file:"
P12_PATH="${P12_PATH/#\~/$HOME}"
if [[ ! -f "$P12_PATH" ]]; then
  warn "No file at $P12_PATH"
  ask P12_PATH "Path to the .p12 file:"
  P12_PATH="${P12_PATH/#\~/$HOME}"
fi
test -f "$P12_PATH" || { warn "Still no file at $P12_PATH"; exit 1; }
ask_secret DEVELOPER_ID_P12_PASSWORD "Password you set on the .p12:"
[[ -n "$DEVELOPER_ID_P12_PASSWORD" ]] || { warn "Password was empty"; exit 1; }
DEVELOPER_ID_P12=$(base64 -i "$P12_PATH" | tr -d '\n')
write_env P12_PATH "$P12_PATH"
note "Certificate will be uploaded as GitHub secret DEVELOPER_ID_P12 in the last stage."

# ── 4. App Store Connect API key (notarytool) ─────────────────────────────
stage "App Store Connect API key"
say "notarytool authenticates with an API key. An Individual key is enough for a solo account."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "App Store Connect → Users and Access → Integrations → App Store Connect API."
step "If you don't have access to team keys, open Individual API keys on that page instead."
step "Copy Issuer ID (UUID at the top of the keys page)."
ask APPSTORE_ISSUER_ID "Paste Issuer ID:"
step "Click Generate API Key (or +). Name it LinkRouter Notary. Access: Developer or Admin."
step "Copy the Key ID (10 characters)."
ask APPSTORE_API_KEY_ID "Paste Key ID:"
step "Download the .p8. Apple only lets you download it once. Don't lose it."
ask P8_PATH "Path to AuthKey_….p8:"
P8_PATH="${P8_PATH/#\~/$HOME}"
if [[ ! -f "$P8_PATH" ]]; then
  warn "No file at $P8_PATH"
  ask P8_PATH "Path to AuthKey_….p8:"
  P8_PATH="${P8_PATH/#\~/$HOME}"
fi
test -f "$P8_PATH" || { warn "Still no file at $P8_PATH"; exit 1; }
APPSTORE_API_PRIVATE_KEY=$(cat "$P8_PATH")
write_env APPSTORE_ISSUER_ID "$APPSTORE_ISSUER_ID"
write_env APPSTORE_API_KEY_ID "$APPSTORE_API_KEY_ID"
write_env P8_PATH "$P8_PATH"

# ── 5. Team ID ────────────────────────────────────────────────────────────
stage "Team ID"
say "This is the 10-character Team ID on your membership card. Codesign needs it."
open_url "https://developer.apple.com/account"
step "Membership details → Team ID."
ask APPLE_TEAM_ID "Paste Team ID:"
[[ "${#APPLE_TEAM_ID}" -eq 10 ]] || warn "Team IDs are usually exactly 10 characters (you entered ${#APPLE_TEAM_ID})."
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"

# ── 6. Upload to GitHub ───────────────────────────────────────────────────
stage "Write GitHub Actions secrets"
say "These go to henrikogaard/linkrouter. The .p12 password and .p8 never get committed."
step "Confirm the values look right, then this step calls gh secret set / gh variable set."
note "Team ID:        $APPLE_TEAM_ID"
note "API Key ID:     $APPSTORE_API_KEY_ID"
note "Issuer ID:      $APPSTORE_ISSUER_ID"
note "p12:            $P12_PATH"
note "p8:             $P8_PATH"
if confirm "Upload signing secrets to GitHub now?"; then
  set_secret DEVELOPER_ID_P12 "$DEVELOPER_ID_P12"
  set_secret DEVELOPER_ID_P12_PASSWORD "$DEVELOPER_ID_P12_PASSWORD"
  set_secret APPSTORE_API_PRIVATE_KEY "$APPSTORE_API_PRIVATE_KEY"
  set_var APPLE_TEAM_ID "$APPLE_TEAM_ID"
  set_var APPSTORE_API_KEY_ID "$APPSTORE_API_KEY_ID"
  set_var APPSTORE_ISSUER_ID "$APPSTORE_ISSUER_ID"
else
  SKIPPED+=("GitHub secret upload (re-run this wizard when ready)")
fi

finish
say "Next: git tag v1.0.0 && git push origin v1.0.0"
say "The Release workflow will Developer ID-sign, notarize, staple, then attach the zip."

